### ISSUE TITLE
documentation error in getting started tutorial

### ISSUE THREAD

**Issue by charleskoehl** [scaphold-io/scaphold-issues#1]
After following instructions in Step 3 of https://scaphold.io/blog/2016/06/14/fastest-way-to-get-started.html, (copying and pasting query and variables) I get the following results:
{
"errors": [
{
"message": "Variable \"$input\" is not defined by operation \"CreateUserMut\"."
},
{
"message": "Variable \"$user\" is never used in operation \"CreateUserMut\"."
}
]
}
I found that this is because there is a typo in Step 3: "createUser(input: $input) {" should be "createUser(input: $user) {"
However, when I correct that, I get the error Will Mruzek got on 9/16, which was this:

Unfortunately I'm getting the following error when trying to create a new user:

"Table `20834461_069c_4dad_b9f6_0a1b9c3a38c6._uniques` does not exist in:\nr.db(\"20834461_069c_4dad_b9f6_0a1b9c3a38c6\").table(\"_uniques\").getAll(\"User.username=johndoe123\", {\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^\n index: \"unique\"\n ^^^^^^^^^^^^^^^\n})\n^ \n"

Any idea what's up?

**Comment by tcastelli** [comment]
Also getting similar error when copying queries from the get started in 5 minutes video but since the user type now doesn't use credentials, I have adapated it to password and username:

The mutation

```
mutation CreateUser($user: _CreateUserInput!){
  createUser(input: $user){
    changedUser{
      id
    }
  }

}
```

The input

```
{
 "user":{
 "username":"randomIKDHSADUH",
 "password":"supersecret"
 }
}

```

The response error

```
{
  "data": {
    "createUser": null
  },
  "errors": [
    {
      "message": "Table `ddc2a3a7_1b21_4340_869a_25266b716d14._uniques` does not exist in:\nr.db(\"ddc2a3a7_1b21_4340_869a_25266b716d14\").table(\"_uniques\").getAll(\"User.username=randomIKDHSADUH\", {\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         ^\n    index: \"unique\"\n    ^^^^^^^^^^^^^^^\n})\n^ \n"
    }
  ]
}
```

**Comment by vning93** [comment]
@charleskoehl @tcastelli: We'll update the docs to reflect that typo, thanks for letting us know! As for the table missing error, I just checked and it should be there now. Hope that resolves your issues!
