### ISSUE TITLE
createX on type w/ nullable [DateTime] field throws

### ISSUE THREAD

**Issue by brandonmp** [scaphold-io/scaphold-issues#18]
`Listing` type has field `openHouseDates: [DateTime]`.  field is not required and is nullable, but executing a `createListing` mutation throws if the `openHouseDates` field isn't present

![image](https://cloud.githubusercontent.com/assets/14139991/23076055/d3213ff0-f50c-11e6-96a5-242d50c07f2e.png)

**Comment by brandonmp** [comment]
problem persists after deleting/recreating the field with the same type (`[DateTime]`)

changing the field to a `[String]`, however, works as expected

**Comment by mikeparisstuff** [comment]
Looking into this now.

**Comment by mikeparisstuff** [comment]
This has been fixed and will go up with the next deployment. Thanks for finding this :)
