### ISSUE TITLE
Unable to delete apps

### ISSUE THREAD

**Issue by iamrobreynolds** [scaphold-io/scaphold-issues#2]
Upon initial login I was prompted with several modal popups to create my first app. After each attempt the window would reappear and I entered the same app name. After refreshing page, the modal stopped appearing and the apps were duplicated many times. When attempting to delete them, they are not removed from https://scaphold.ios/ list.

**Comment by vning93** [comment]
Thanks for raising the issue. That's definitely some unexpected behavior. Would you like me to delete the apps you don't want? I'll personally reach out to you for your API key.
