### ISSUE TITLE
V2: submitting request in graphiql resets query and query variables when result displays

### ISSUE THREAD

**Issue by MacKentoch** [scaphold-io/scaphold-issues#3]
**V2 - graphiql: submitting a request resets query and query variables when result displays**

I first thought it was intented. But clicking history button reveals that even history does not save previous query.

_In V1: queries persisted and history registered all query._
- any query or mutation (with or without variables)
  ![sample request before submitting](https://raw.githubusercontent.com/MacKentoch/scaphold-contrib-statics/master/print_screens/V2/before-request-submit.png)
- result displays as intended but it resets query
- history did not register the query (history remains empty)
  ![sample request after submitting](https://raw.githubusercontent.com/MacKentoch/scaphold-contrib-statics/master/print_screens/V2/after-request-submit.png)

> it is not critical but just a comfort 😄

**Comment by MacKentoch** [comment]
It does no more occur.

History button has disapeared but it is not an issue for me.

I close this issue.

**Comment by vning93** [comment]
No problem. Thanks for letting us know. We'll get the history button up for you shortly.
Vince

On Sat, Oct 22, 2016 at 6:39 PM -1000, "Erwan DATIN" notifications@github.com wrote:

It does no more occur.

History button has disapeared but it is not an issue for me.

I close this issue.
