### ISSUE TITLE
V2: CreateUser mutation returns a null token in its payload

### ISSUE THREAD

**Issue by MacKentoch** [scaphold-io/scaphold-issues#4]
I'm talking about V2.

`CreateUser` mutation does its job: creating a user.

But `CreateUserPayload` returns a null token.

It is a bit annoying since I have to call `LoginUser` mutation after a `CreateUser` mutation to get the user token.

This:

``` graphql
 mutation CreateUser ($user: CreateUserInput!) {
    createUser (input: $user) {
        changedUser {
            id
            username
        }
        token
    }
}
# variables:
{
  "user": {
    "username": "test2",
    "password": "test2"
  }
}  
```

gives:

``` javascript

{
  "data": {
    "createUser": {
      "changedUser": {
        "id": "VXNlcjo3",
        "username": "test2"
      },
      "token": null
    }
  }
}
```

**Comment by vning93** [comment]
Hi, thanks for letting us know! I've made the fix, and will push the changes up altogether with a couple other things tomorrow evening.

Best,
Vince

**Comment by MacKentoch** [comment]
hi @vning93, 

Thank you once again 👍

**Comment by vning93** [comment]
No problem!

Get Outlook for iOS

On Mon, Oct 24, 2016 at 9:13 AM -1000, "Erwan DATIN" notifications@github.com wrote:

hi @vning93, 

Thank you once again 👍

**Comment by MacKentoch** [comment]
hi @vning93 ,

Maybe I missed something since I still have a null token with `createUser` mutation...

By the way: if I invest so much time in short term it is because I'm trying to create an open source starter project based on scaphold as backend: [react redux _zero pain graphql backend_ apollo-starter](https://github.com/MacKentoch/react-redux-graphql-apollo-bootstrap-webpack-starter#prerequisite).

The idea behind this starter, is to have:
- a fast starter for my best front-end stack (react-redux)
- combining graphql (+ Apollo client)
- with no pain in having a graphql backend thanks to scaphold 
  - speed of light backend
  - free plan is enough for dev
  - paid plan are better compared to firebase for instance

**Comment by MacKentoch** [comment]
fixed, thanks!

**Comment by vning93** [comment]
Awesome, no problem. Apologies for not letting you know here, but we just pushed up a ton of fixes the other day.

Let me know if you find anything else 👍
