### ISSUE TITLE
Scaphold website navigation bar style issue on Safari 10.0.1

### ISSUE THREAD

**Issue by MacKentoch** [scaphold-io/scaphold-issues#5]
Hi,

*In a severity scale from 1 to 10, I would give 0.01 to this issue* :smile:

I did not notice if it occurred during V2 early access (I always connected in chrome) but on `Safari 10` there is a `style issue` on `navigation bar` (*navigation bar takes 74px height in Safari versus 60px height in Chrome*):

![print sreen](https://raw.githubusercontent.com/MacKentoch/scaphold-contrib-statics/master/print_screens/V2/navbar_on_safari.png)

On landing page, it is just an aesthetic issue but on application screen it is a bit more annoying (*left side bar top or right content is a bit hidden*).

**Comment by vning93** [comment]
Got it, thanks for raising the issue. We'll get it fixed up for Safari browsers shortly!
