### ISSUE TITLE
I can not edit/delete permissions

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [scaphold-io/scaphold-issues#8]
Hi! When trying to delete a permission or editing it, I get this error:

![error](https://cloud.githubusercontent.com/assets/12840136/21487889/247a0c24-cbbe-11e6-86e6-f33131a99c72.png)

PS: The UI does not show any indication of the error

**Comment by vning93** [comment]
Hi! Looks like you're trying to apply a non-null constraint on a particular field with null data in the DB already, which is not allowed. Can you refresh, check and make sure that you're not trying to update a non-null constraint on a field with data that has null values?

**Comment by mikeparisstuff** [comment]
This issue has been fixed. Thanks for raising!
